### ISSUE TITLE
Broken link to demo site

### ISSUE THREAD

**Issue by jmooring** [khusika/FeelIt#104]
See https://github.com/gohugoio/hugo/issues/10612

> Please remove the Demo button on the page https://themes.gohugo.io/themes/feelit/. It redirect to a different unsecure site on each click

**Comment by khusika** [comment]
> See [gohugoio/hugo#10612](https://github.com/gohugoio/hugo/issues/10612)
> 
> > Please remove the Demo button on the page https://themes.gohugo.io/themes/feelit/. It redirect to a different unsecure site on each click

Thanks, i'll take a look into it

**Comment by khusika** [comment]
Fixed
https://themes.gohugo.io/themes/feelit/
