### ISSUE TITLE
[FEATURE] Add parameters to adjust the page width

### ISSUE THREAD

**Issue by zu1k** [khusika/FeelIt#16]
Would you please add a param to let us adjust the page width?

For example:

```
width: 80  # Percentage of page width

or

width: "wide" # compact\normal\wide
```

**Comment by khusika** [comment]
> Would you please add a param to let us adjust the page width?
> 
> For example:
> 
> ```
> width: 80  # Percentage of page width
> 
> or
> 
> width: "wide" # compact\normal\wide
> ```

It's technically possible to do this using `data-attributes`, but adding more `data-attributes` for one parameter makes the css size increase with redundant css properties. it will be even simpler if you change the value inside [_override.scss](https://github.com/khusika/FeelIt/blob/main/exampleSite/assets/css/_override.scss) with `!important` rules. For example:

```
// assets/css/_override.scss
// Override Variables

@media only screen and (max-width: 2560px) {
  .page {
    width: 70% !important;
  }
}
```

**Comment by zu1k** [comment]
Thank you for your reply. 

I've actually been modifying it this way so far, but I'm finding that there are more attributes that need to be modified. Not only do I need to make separate changes for different sized devices, but I also need to consider modifying the location of the toc otherwise it will leave a large spacing. 

So I want a reserved style option, such as compact/normal/wide, to be able to modify these multiple attributes at the same time.

For the css redundancy issue, I wonder if it is possible to use conditions to control the css output, instead of selecting different css properties by class.

**Comment by khusika** [comment]
> So I want a reserved style option, such as compact/normal/wide, to be able to modify these multiple attributes at the same time.

Sorry for the late responses,
Can you be more specific? which page size do you mean? is it entire `page` or only for `single` class?

**Comment by zu1k** [comment]
> is it entire `page` or only for `single` class?

entire pages including posts, simple pages, archive page, list page, tag page, category page, etc.

**Comment by khusika** [comment]
> entire pages including posts, simple pages, archive page, list page, tag page, category page, etc.

I do agree if the user chooses the page size they want,
but come back again that this will cost a lot of redundant resources as I mentioned before.

> It's technically possible to do this using `data-attributes`, but adding more `data-attributes` for one parameter makes the css size increase with redundant css properties.

Even using [PurgeCSS as postcss](https://github.com/khusika/FeelIt/commit/606da746abd9ad22e1ca113e561de9bcc2017c3e) can't handle the removal unused css (cause every single class were mentioned in html template).

So I choose not to make any changes about this and it think the current page-sizes is good enough for us.
