### ISSUE TITLE
[FEATURE] Typlog image content

### ISSUE THREAD

**Issue by horusra** [khusika/FeelIt#20]
https://blog.typlog.com/images

Can you please add support for this?
It allows for easily organizing images in content, making them fit properly in page.
It was also implemented in hugo for this theme: 
https://docs.stack.jimmycai.com/writing#insert-image
https://github.com/CaiJimmy/hugo-theme-stack/

**Comment by khusika** [comment]
> https://blog.typlog.com/images
> 
> Can you please add support for this?
> It allows for easily organizing images in content, making them fit properly in page.
> It was also implemented in hugo for this theme:
> https://docs.stack.jimmycai.com/writing#insert-image
> https://github.com/CaiJimmy/hugo-theme-stack/

I'll choose to upgrade LightGallery to version 2 instead of using this

**Comment by horusra** [comment]
@khusika 
> I'll choose to upgrade LightGallery to version 2 instead of using this
> https://www.lightgalleryjs.com/

Wow, that looks great! LightGallery v2 would indeed be preferable over Typlog.
