### ISSUE TITLE
[FEATURE] RSS expansion

### ISSUE THREAD

**Issue by horusra** [khusika/FeelIt#21]
Right now, the RSS feed generated by Feelit only includes the title and first line of the content.
It would be great to add an option in the site config to expand RSS feed to include the complete post (including images) like some other blogs do.

Feelit RSS post:
![image](https://user-images.githubusercontent.com/17074394/123528713-e6a18080-d6e9-11eb-9e90-bac60d531345.png)

RSS post of different site that even includes the audio of the podcast:
![image](https://user-images.githubusercontent.com/17074394/123528738-1cdf0000-d6ea-11eb-856e-d8214549341f.png)
https://your-undivided-attention.simplecast.com/episodes/down-the-rabbit-hole-by-design-ZckVqGxb

**Comment by khusika** [comment]
> Right now, the RSS feed generated by Feelit only includes the title and first line of the content.
> It would be great to add an option in the site config to expand RSS feed to include the complete post (including images) like some other blogs do.

RSS Feed seems like to old for us, it's better to implement [PWA](https://developers.google.com/web/updates/2015/12/getting-started-pwa) and keeping the current RSS configuration. And i have plan to implement this ASAP

**Comment by horusra** [comment]
PWA would be awesome!
