### ISSUE TITLE
[FEATURE] Add GoatCounter Analytic

### ISSUE THREAD

**Issue by horusra** [khusika/FeelIt#23]
It seems the current analytics support built in is Fanthom Analytics.
I suggest adding [GoatCounter ](https://www.goatcounter.com/) as an optional analytics service.
It is permanently free for:

- Unlimited sites
- 100k pageviews/month
- 2.4M maximum pageviews 

This should cover most people.

**Comment by khusika** [comment]
> It seems the current analytics support built in is Fanthom Analytics.
> I suggest adding [GoatCounter ](https://www.goatcounter.com/) as an optional analytics service.
> It is permanently free for:
> 
> * Unlimited sites
> * 100k pageviews/month
> * 2.4M maximum pageviews
> 
> This should cover most people.

This theme has **_Fanthom_** and **_Google Analytics_** (_Both Google Analytic and Google Tag Manager support_) for analytics support. You can choose Google Analytic support if you are looking for free stuff.

**Comment by horusra** [comment]
Yes, however google analytics is a lot heavier and requires cookie notice as per GDPR. 
GoatCounter is a lot smaller in footprint and doesn't require any notices because it's privacy focused.

**Comment by khusika** [comment]
> Yes, however google analytics is a lot heavier and requires cookie notice as per GDPR. 
> GoatCounter is a lot smaller in footprint and doesn't require any notices because it's privacy focused. 

I'll take a look into it
