### ISSUE TITLE
[FEATURE] Optimization, icons and Font Awesome

### ISSUE THREAD

**Issue by horusra** [khusika/FeelIt#24]
I'm not sure how feasible this is to implement, but having to retrieve icons from font awesome adds unnecessary overhead when all we needs is an svg (that we can get from many sources).

More info and demonstration:
[Short Youtube Video](https://www.youtube.com/watch?v=or7amkb0Pk8)
[![](https://img.youtube.com/vi/or7amkb0Pk8/0.jpg)](https://www.youtube.com/watch?v=or7amkb0Pk8)

As you can see, from the video, getting rid of font awesome is fairly easy, it makes the site faster, and also allows the user to use [Iconify](https://iconify.design/) which means they will have many more icon libraries to choose from.

The way he does it in the video is an option (svg code), but we can also just download the svg file and just link to it locally.

![image](https://user-images.githubusercontent.com/17074394/123532258-ff229280-d70b-11eb-8590-fad75f18da01.png)
in this example I'm trying to add [Artstation](https://artstation.com) to social.yml but since Font Awesome doesn't include its icon in the free pack, I have no option. 
But using the method in that video, I can use iconify and get many icons from many libraries, and without having to change implementation since I would get the actual svg.
![image](https://user-images.githubusercontent.com/17074394/123532299-59bbee80-d70c-11eb-8c1f-748c6c8d4ace.png)
https://github.com/iconify

**Comment by khusika** [comment]
> I'm not sure how feasible this is to implement, but having to retrieve icons from font awesome adds unnecessary overhead when all we needs is an svg (that we can get from many sources).

I'll keep to use both Font-Awesome and Simple-Icon for font resources which has lot of icon support. I just wanna avoid lot of request related to the icon implementation (cause of the limitation)

Reducing unused resources are can be done using [PurgeCSS](https://purgecss.com/). You can use [PurgeCSS with post-cli](https://github.com/khusika/FeelIt/commit/606da746abd9ad22e1ca113e561de9bcc2017c3e) or simplify using [PurgeCSS as pre-commit](https://github.com/khusika/khusika.github.io/commit/65da595455bb8ad8f4998abe167408ed021e8c2a)
