### ISSUE TITLE
Build issue - template for shortcode not found

### ISSUE THREAD

**Issue by pathakraul** [khusika/FeelIt#26]
### Description

I have hugo extended install and trying to run the examplesite but getting the errors for all the short codes

```
FeelIt$ hugo version
hugo v0.84.4-020E4ACE+extended linux/amd64 BuildDate=2021-07-01T11:51:55Z VendorInfo=gohugoio
FeelIt$ 
FeelIt$ hugo serve --source=exampleSite
Start building sites … 
hugo v0.84.4-020E4ACE+extended linux/amd64 BuildDate=2021-07-01T11:51:55Z VendorInfo=gohugoio
Built in 42 ms
Error: Error building site: "FeelIt/exampleSite/content/about/index.fr.md:12:1": failed to extract shortcode: template for shortcode "style" not found
```

### Build Environment

- OS: Ubuntu 20.04
- Theme version: main branch latest commit
- Hugo version: 84.4

**Comment by khusika** [comment]
> ### Description
> I have hugo extended install and trying to run the examplesite but getting the errors for all the short codes
> 
> ```
> FeelIt$ hugo version
> hugo v0.84.4-020E4ACE+extended linux/amd64 BuildDate=2021-07-01T11:51:55Z VendorInfo=gohugoio
> FeelIt$ 
> FeelIt$ hugo serve --source=exampleSite
> Start building sites … 
> hugo v0.84.4-020E4ACE+extended linux/amd64 BuildDate=2021-07-01T11:51:55Z VendorInfo=gohugoio
> Built in 42 ms
> Error: Error building site: "FeelIt/exampleSite/content/about/index.fr.md:12:1": failed to extract shortcode: template for shortcode "style" not found
> ```
> 
> ### Build Environment
> * OS: Ubuntu 20.04
> * Theme version: main branch latest commit
> * Hugo version: 84.4

Have you tried to follow "[Getting Started](https://github.com/khusika/FeelIt#getting-started)" instruction?

**Comment by pathakraul** [comment]
I only did the `npm run preinstall` and was facing issues with other commands. 
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! feelit-src@1.0.0 babel: `npx babel src/js --out-file assets/js/theme.min.js --source-maps && npx babel src/js --out-file assets/js/themes.min.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the feelit-src@1.0.0 babel script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-02T08_44_29_376Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! feelit-src@1.0.0 build: `rm -f -r exampleSite/public && npm run babel && hugo -v --source=exampleSite --themesDir ../ --gc`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the feelit-src@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-02T08_44_29_386Z-debug.log
```
I thought that since these short codes are also present in Loveit and other forks which does not cause the issue then it should build without these documentation build

Excuse my knowledge on npm and its ecosystem

**Comment by khusika** [comment]
> I only did the `npm run preinstall` and was facing issues with other commands.
> 
> ```
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! feelit-src@1.0.0 babel: `npx babel src/js --out-file assets/js/theme.min.js --source-maps && npx babel src/js --out-file assets/js/themes.min.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the feelit-src@1.0.0 babel script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2021-07-02T08_44_29_376Z-debug.log
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! feelit-src@1.0.0 build: `rm -f -r exampleSite/public && npm run babel && hugo -v --source=exampleSite --themesDir ../ --gc`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the feelit-src@1.0.0 build script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2021-07-02T08_44_29_386Z-debug.log
> ```
> 
> I thought that since these short codes are also present in Loveit and other forks which does not cause the issue then it should build without these documentation build
> 
> Excuse my knowledge on npm and its ecosystem

Can you attach the log output?

**Comment by pathakraul** [comment]
Hi, I had the issue with the babel version and then I was installing it using -g. I installed it locally then the npm commands worked.

hugo server --source=exampleSite still does not work though.

**Comment by khusika** [comment]
> Hi, I had the issue with the babel version and then I was installing it using -g. I installed it locally then the npm commands worked.
> 
> hugo server --source=exampleSite still does not work though.

Try this
`npm run reinstall && npm run start-production `
