### ISSUE TITLE
[FEATURE] Improve svg-icons automation for favicon

### ISSUE THREAD

**Issue by horusra** [khusika/FeelIt#34]
When using SVG, should it not override all other favicons?

the files in example site static folder:
![image](https://user-images.githubusercontent.com/17074394/125210153-35304c80-e29e-11eb-8c27-ee39fa9a1870.png)
site example config:
![image](https://user-images.githubusercontent.com/17074394/125210168-4bd6a380-e29e-11eb-8330-038c008c1cf6.png)

microsoft edge app install (here it shows svg):
![image](https://user-images.githubusercontent.com/17074394/125210281-167e8580-e29f-11eb-99f6-f56c60d9569c.png)
app install confirmation (here it shows favicon instead)
![image](https://user-images.githubusercontent.com/17074394/125210293-30b86380-e29f-11eb-8b4e-4c0f37d8aaa9.png)

windows tile:
![2223](https://user-images.githubusercontent.com/17074394/125210177-58f39280-e29e-11eb-8ead-c8918d91ee80.jpg)
taskbar tile:
![image](https://user-images.githubusercontent.com/17074394/125210195-758fca80-e29e-11eb-9691-f59d91b7b0f3.png)

**Comment by khusika** [comment]
> When using SVG, should it not override all other favicons?

Declare your svg icon on [site.webmanifest](https://github.com/khusika/FeelIt/blob/main/exampleSite/static/site.webmanifest)

**Comment by khusika** [comment]
Currently, Hugo does not support SVG image processing. So, the only way is to do it manually.
