### ISSUE TITLE
[BUG] local preview broken after converting images to webp

### ISSUE THREAD

**Issue by Sp-cy** [khusika/FeelIt#51]
### Describe the bug

After changing a lot of the images in my blog to webp, the local preview in Hugo broke. It was working reasonably well before. Style sheets are not loading neither images in my local preview but they do work in the live site.

### Expected behavior

locally built preview should look like almost the live website 

### Screenshots

![firefox_QFSdX20YSV](https://user-images.githubusercontent.com/68587155/127489774-7b2a5087-5d28-429c-9c30-e2234688c1bb.png)

![firefox_BL2WPUcbuv](https://user-images.githubusercontent.com/68587155/127489799-b72a8b13-0bc5-4c1f-9779-9bef1498cd31.png)

I do get errors in Firefox's Inspector

![firefox_NlH50Qet2G](https://user-images.githubusercontent.com/68587155/127491338-d3ab1e9d-1a3c-4792-a843-a947e7f68d1b.png)

![firefox_Jdet9GcVnz](https://user-images.githubusercontent.com/68587155/127491357-8404c3e8-f575-4295-8559-b89d21d40d6b.png)

### Build Environment

- OS: Windows 10
- Theme version/commit: 1.0.1
- Hugo version: 0.86.0 extended
Please try to use Hugo **extended** version before opening the issue.

### Preview Environment

- OS: Windows 10
- Browser:  Firefox

### Additional Information

Hugo doesn't display any errors in the terminal after getting the hugo serve --disableFastRender command.

Thank you in advance for any help. Love what you have done with this theme. I can FeelIt.

**Comment by khusika** [comment]
Probably you didn't set the `themsDir` properly

```
theme = "FeelIt"
themesDir = "themes"

```

**Comment by Sp-cy** [comment]
You were right. The themesDir wasn't setup. I did set it up now and it's still broken. But I'm suspecting it might be a Hugo error because while checking on Edge browser if I got the same errors I realized I get the pages to display if I press "CNTRL + F5". If i reload the page using the reload button or just F5 I still see the broken page. It's really confusing.

**Comment by khusika** [comment]
> You were right. The themesDir wasn't setup. I did set it up now and it's still broken. But I'm suspecting it might be a Hugo error because while checking on Edge browser if I got the same errors I realized I get the pages to display if I press "CNTRL + F5". If i reload the page using the reload button or just F5 I still see the broken page. It's really confusing. 

Try to disable PWA for debugging

**Comment by Sp-cy** [comment]
ok. Just did it.  With this in the config file

```
  # PWA config
  [params.pwa]
    # whether to enable PWA support
    enable = false
    # service-worker version
    version = "1.0.1"
``` 
the service worker stays alive in the browser. But after unregistering the service worker in the browser by pressing F12 then going to the Application tab and pressing "Unregister" in the service worker, everything is working smooth again. Same thing worked both in Firefox and Edge Browser. I guess the service worker's cache is messing with the preview when some changes happen. But I really don't know much. This works for me now, thank you for your knowledge. My blog is hosted in https://blog.sp-cy.com/ if you want to check it out, it's mostly goofy gaming posts but with your theme it looks lovely. I guess you can close the issue if you think that un-register the service worker in the browser while previewing is the ideal solution for now.  Thanks again!
