### ISSUE TITLE
[FEATURE] update the version of mermaid

### ISSUE THREAD

**Issue by chengleqi** [khusika/FeelIt#53]
### Describe the feature you want

- I drew a flowchart, it can be shown correctly in the [Mermaid v8.11.2 Live Editor](https://mermaid-js.github.io/mermaid-live-editor/edit#eyJjb2RlIjoiZmxvd2NoYXJ0IEJUXG4gICAgZGlyZWN0aW9uIEJUXG4gICAgc3ViZ3JhcGggbG9jYWxfd29ya2Zsb3dcbiAgICAgICAgZGlyZWN0aW9uIFJMXG4gICAgICAgIEEtLT5857yW5YaZbWFya2Rvd27lubbkvb_nlKjmj5Lku7bpooTop4h8WShkaXNrKVxuICAgICAgICBZLS0-fOaMgui9veWNmuWuouebruW9lXxCKGRvY2tlcilcbiAgICAgICAgQi0tPnzmmKDlsIQxMzEz56uv5Y-jfFgoYnJvc3dlcilcbiAgICAgICAgWC0tPnzlrp7ml7bpooTop4h8QSgodnNjb2RlKSlcbiAgICBlbmRcbiAgICAgICAgbG9jYWxfd29ya2Zsb3ctLT58Z2l0IHB1c2h8Qyhzb3VyY2UgcmVwbylcbiAgICBzdWJncmFwaCBnaXRodWJfYWN0aW9uc19DSS9DRF9waXBsaW5lXG4gICAgICAgIGRpcmVjdGlvbiBMUlxuICAgICAgICBEKHNldHVwIGVudiktLT5FKGNoZWNrb3V0KS0tPkYoc2V0dXAgaHVnbyktLT5HKGJ1aWxkKS0tPkgoZGVwbG95KVxuICAgIGVuZFxuICAgIEMtLT58cHVzaOinpuWPkWdpdGh1Yl9hY3Rpb25zfGdpdGh1Yl9hY3Rpb25zX0NJL0NEX3BpcGxpbmVcbiAgICBzdWJncmFwaCBnaXRodWIuaW9fcmVwb1xuICAgICAgICBkaXJlY3Rpb24gUkxcbiAgICAgICAgSihkb21haW4pLS0-fENOQU1FfEkoZ2l0aHViLmlvKVxuICAgIGVuZFxuICAgIGdpdGh1Yl9hY3Rpb25zX0NJL0NEX3BpcGxpbmUtLT585L2_55SocGVyc29uYWxfdG9rZW7mjqjpgIHliLBnaXRodWIuaW9fcmVwb3xnaXRodWIuaW9fcmVwbyIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkZWZhdWx0XCJcbn0iLCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6ZmFsc2V9), but when I copy the mermaid code into the `{{< mermaid >}} {{< /mermaid >}}` shortcode , I got nothing on `hugo server` preview. Then I found the flowchart can only be used in hign version  https://mermaid-js.github.io/mermaid/#/flowchart?id=beta-flowcharts, mermaid released v8.11.2 3 days ago, but Feelit theme use v8.5.1. I'm not familiar with front end.I don't know how to update the version myself.Could you update the version of mermaid, please.

### Useful reference

https://github.com/mermaid-js/mermaid/releases

**Comment by khusika** [comment]
First of all I had plans to update the mermaid version which I was doing on PR #54, but I had to put it on hold due to some broken internal API calls mentioned in mermaid [issues #1034](https://github.com/mermaid-js/mermaid/issues/1034) which is effected on the dark-theme mode.

About the flowchart issue, it should work with the current version 8.5.1 [theme-documentation#flowchart](https://feelit.khusika.com/theme-documentation-extended-shortcodes/#flowchart).

**Comment by chengleqi** [comment]
I tried again but it still couldn't be shown with the current version 8.5.1![image](https://user-images.githubusercontent.com/53958238/127959992-e56692a0-145e-4b68-9fee-697b65e0d25c.png)

**Comment by khusika** [comment]
> I tried again but it still couldn't be shown with the current version 8.5.1

Hmm, seems like you were right.

If you are really need it ASAP you can apply the temporary workaround from #54 (All things good with your Flowchart code)
![Screenshot from 2021-08-03 12-19-00](https://user-images.githubusercontent.com/5193379/127961893-b1136873-0f7c-40e5-9aa6-3676667bdb45.png)

**Comment by chengleqi** [comment]
OH, I use a image instead.
Looking forward to your PR😀. 
Thank you for nice work

**Comment by chengleqi** [comment]
It worked! thank u!
