### ISSUE TITLE
[FEATURE] Microblogging capability

### ISSUE THREAD

**Issue by Sp-cy** [khusika/FeelIt#58]
Hi! I currently use 2 different themes for different types of posts. I use FeelIt for a traditional structure blog type of posts and I use another one for a more casual and unstructured micro blogging type of posts. After seeing what you've been doing with the about theme I thought I could suggest you to add some micro blogging section or capabilities to have that kind of posts in the main list/grid view. I like the [POSSE](https://indieweb.org/POSSE) approach that is compatible with webmentions referred in [Issue 19](https://github.com/khusika/FeelIt/issues/19) and prefers posting first own your site and then reposting in social websites. If you feel like adding this feature to the site I guess it's up to you if this should be in it's own section (this could allow it to live in it's own subdomain) or just get integrated in the homepage.

- It would be useful if they had the social sharing buttons in the single page so we could repost easily from our sites.
- Microblog posts don't require a title or subtitle, it's mostly {{content}} , {{img resources}} and or {{link}} {{video link}}. Adding a video capability to lightgallery when bumped to v2 would probably be helpful for keeping low loadtimes and also maintain the aesthetics of the theme. 

### Useful references

This is my micro blog: 
https://micro.sp-cy.com/en/

for now I just link to it from the blog with a "microblog" font awesome icon in the header.
![image](https://user-images.githubusercontent.com/68587155/128614137-a9faa5ea-f0a5-47a4-b9fc-fbdcd57f2904.png)
 

This are some sites that have some kind of blog/microblog co-existence: 

https://aaronparecki.com/
https://tantek.com/

I'll understand if you aren't interested in this feature since it may be out of focus and hard to implement.  Much love Khusika.

**Comment by khusika** [comment]
Hi, this is first time i heard about _micro-blogging_ which is refer to the [microformats.org](https://microformats.org/). It is technically possible to create a sort of _microblog_ under the "_micro_" or "_notes_" section instead of "post".

Because the contents of blogs and microblogs are different, there are lot of concerns to make it possible. For example is making the _terms_ (both _tags_ and _categories_) separation between post and micro sections with hugo-processing. Those also affect to the _sitemap_ and page _indexing_.

**Comment by Sp-cy** [comment]
Tags and categories aren't necessary in micro blog posts. I have no solution for the sitemap and page indexing but I don't know much about web dev. I'll inspect some sites of people that micro blog and see what they do. Thanks for your answer.

**Comment by Sp-cy** [comment]
I just realized there's no reporting of the tags params in most hugo sites because unlike what is stated in the docs, the open graph internal template doesn't populate or report any meta article:tags. I just reported the [issue](https://github.com/gohugoio/hugo/issues/8875) on the Hugo repo. Only the [Schema internal template](https://github.com/gohugoio/hugo/blob/master/tpl/tplimpl/embedded/templates/schema.html) reports any article tags as <meta itemprop="keywords"  in the <head>.

**Comment by khusika** [comment]
> I just realized there's no reporting of the tags params in most hugo sites because unlike what is stated in the docs.

what I mean is that _tags_ and _categories_ cannot be separated from _blog_ and _micro-blog_. Both of them will be automatically merged in `/tags` & `/categories`.

> Tags and categories aren't necessary in micro blog posts.

Isn't that looks weird writing a post without tags/categories in nowadays?

---

And yet i still have no idea why we need to implement both _micro-blogging_ and _blogging_ into a one-site. Most people (on the internet) do _micro-blogging_ on the social media rather than personal sites. 😕

**Comment by Sp-cy** [comment]
sorry I think i should have submitted a new issue. This is related to tags but not entirely to the feature request.
Go to your site, or my site. Press f12 in browser and see how we don' t have either article:tags nor itemprop= "keywords". 

Now check this site:
https://demo.stack.jimmycai.com/p/markdown-syntax-guide/

and he does have the tags reported in the head. 
Hugo is wrongly stating that the opengraph internal template does this on it's own. 

sorry for posting this here since it only added to the confusion. 

I'm keeping my microblog separate from the blog, that's fine. 
And I disagree with the censoring that social media has been doing even if I disagree with the people they censor. They make their sites addictive, they harvest people' s personal data, you don' t own your content, they let hostile actors impersonate females, etc. and don't think they should be allowed to do that. But that is just my personal opinion. 

What I wanted to express with my last answer was related to the general stating of the tags in this and most Hugo themes caused by wrong statements in Hugo's documentation.
Tags were supposed to be helpful for SEO crawlers but since they are not stated in the HEAD of the site, they aren't used by them in this theme. They should look like this:
![image](https://user-images.githubusercontent.com/68587155/128977338-9cb827fd-bbec-4f50-bdda-56b3ef341f27.png)


Greetings Khusika.

**Comment by khusika** [comment]
> Go to your site, or my site. Press f12 in browser and see how we don' t have either article:tags nor itemprop= "keywords".
> ![image](https://user-images.githubusercontent.com/68587155/128977338-9cb827fd-bbec-4f50-bdda-56b3ef341f27.png)
> 

`article:tags` is unnecessary cause no website(as far as i know) read those meta tag (read the [discussion here](https://webmasters.stackexchange.com/a/86922)). And also we have defined the `keywords` in [SEO#L111-L113](https://github.com/khusika/FeelIt/blob/main/layouts/partials/head/seo.html#L111-L113).

You can test it on every FeelIt-post with every SEO debugger and no warnings are reported:

- [Google Rich-Test-Result](https://search.google.com/test/rich-results)
- [Schema Validator](https://validator.schema.org/)
- [Pinterest Debugger](https://developers.pinterest.com/tools/url-debugger/)
- [Facebook Debugger](https://developers.facebook.com/tools/debug/)
- [Twitter Card Validator](https://cards-dev.twitter.com/validator)

Note:
Facebook debugger will warn undefined `fb:app_id`, which will be deprecated in the latest Facebook API. And also the bigger image sizes will not be loaded.

**Comment by Sp-cy** [comment]
I hadn't noticed that they are reported in the SEO script tag. Thanks for your answer!
