### ISSUE TITLE
[HELP] Auto-deploy to Netlify fails "merge not defined"

### ISSUE THREAD

**Issue by robpetrin** [khusika/FeelIt#59]
### Describe the bug

I noted [the docs](https://feelit.khusika.com/theme-documentation-basics/#26-build-the-website) say you can automatically deploy to Netlify, which is great. Every time I try, I get the error in the screenshot below "merge not defined."

### Expected behavior

A successful build to Netlify :) I plan to configure directly on GitHub to tweak things here and there but I don't have much in mind to update the taxonomy, schema, or theme itself.

### Screenshots

![image](https://user-images.githubusercontent.com/20173621/128637360-c589620e-2c8f-4147-81ad-022a1a5e81ca.png)

### Build Environment

- OS: Netlify so Linux??
- Theme version/commit: [e.g. 1.0.0, [64a8b8a2d](https://github.com/khusika/FeelIt/commit/64a8b8a2d64b89f918abdb4a6c4ccba888bc98bd)]
- Hugo version: [e.g. 0.84.0] presumably 0.84.0 extended, since I did not update theme.toml

### Preview Environment

N/A

### Additional Information

I love this theme!

**Comment by khusika** [comment]
This is not bug related, you may calling the theme in a wrong way.

I assume you were using [this repo](https://github.com/robpetrin/FeelIt) to deploy it on the netlify, i saw you were mixing web-content with the theme folder in [this commit](https://github.com/robpetrin/FeelIt/commit/dcc275d9932caf18a2cad10bea6f90c06c742881).

You can do this instead:
**1st Method**
- /YourWebContent
- /YourWebContent/themes/FeelIt

**2nd Method**
- /FeelIt
- /FeelIt/YourWebContent

Don't forget to define both `theme` and `themesDir` in your `config.toml`
