### ISSUE TITLE
[BUG] Google Analytics does not work

### ISSUE THREAD

**Issue by gatolynx** [khusika/FeelIt#61]
### Describe the bug

When I add in `config.toml`
```
googleAnalytics = "UA-hoge"
[privacy]
  [privacy.googleAnalytics]
    disable = false
    anonymizeIP = true
    respectDoNotTrack = true
```
Render error occuered, such as
```
ERROR 2021/08/15 05:31:06 render of "page" failed: execute of template failed: template: _internal/google_analytics.html:1:16: executing "_internal/google_analytics.html" at <.Site.Config.Privacy.GoogleAnalytics>: can't evaluate field Site in type string
ERROR 2021/08/15 05:31:06 render of "page" failed: execute of template failed: template: _internal/google_analytics.html:1:16: executing "_internal/google_analytics.html" at <.Site.Config.Privacy.GoogleAnalytics>: can't evaluate field Site in type string
ERROR 2021/08/15 05:31:06 render of "page" failed: execute of template failed: template: _internal/google_analytics.html:1:16: executing "_internal/google_analytics.html" at <.Site.Config.Privacy.GoogleAnalytics>: can't evaluate field Site in type string
ERROR 2021/08/15 05:31:06 render of "page" failed: execute of template failed: template: _internal/google_analytics.html:1:16: executing "_internal/google_analytics.html" at <.Site.Config.Privacy.GoogleAnalytics>: can't evaluate field Site in type string
ERROR 2021/08/15 05:31:06 Rebuild failed:
```

### Expected behavior

google analytics(google tagmanagers ) tags displayed in header.

### Build Environment

- OS: Alpine ... docker [peaceiris/hugo:v0.87.0](https://hub.docker.com/layers/peaceiris/hugo/v0.87.0-full/images/sha256-5fef4aec15f274a59b7bdee4a34b884b8d68f8aac3d42a29c6e6422362191afc?context=explore)
- Theme version/commit: [1.0.1](https://github.com/khusika/FeelIt/commit/4d3c643f10194995549965c6e3e11790177cdae1)
- Hugo version: [v0.87.0-B0C541E4+extended]

Please try to use Hugo **extended** version before opening the issue.

### Preview Environment

- OS: [macOS]
- Browser [Chrome]

### Additional Information

I think With is Rebinds the context (.) , Internal Templates can not use arguments correct config.

in`baseof.html`
```
{{- $analytics := .Site.Config.Privacy.GoogleAnalytics -}}
        {{- if not $analytics.Disable }}{{ with .Site.GoogleAnalytics -}}
            {{ template "_internal/google_analytics.html" . }}
        {{- end -}}{{ end -}}
```
"_internal/google_analytics.html" arguments were rebinded `.Site.GoogleAnalytics` by With.

I think this should be fix below.
```
{{- $analytics := .Site.Config.Privacy.GoogleAnalytics -}}
        {{- if not $analytics.Disable }}{{ if .Site.GoogleAnalytics -}}
            {{ template "_internal/google_analytics.html" . }}
        {{- end -}}{{ end -}}
```

**Comment by khusika** [comment]
Hi, thanks for your report.

I'll prefer to use `if and` as conditional statement instead
