### ISSUE TITLE
[FEATURE] "Now" Page standard

### ISSUE THREAD

**Issue by horusra** [khusika/FeelIt#63]
### Now page
Most websites have a link that says “**about**”. It goes to a page that tells you something about the background of this person or business. For short, people just call it an “about page”.

Most websites have a link that says “**contact**”. It goes to a page that tells you how to contact this person or business. For short, people just call it a “contact page”.

So a website with a link that says “**now**” goes to a page that tells you **what this person is focused on at this point in their life**. For short, we call it a “now page”. 

It was coined by [Derek Sivers here](https://sive.rs/nowff)

---

### Examples of Now pages:

https://8-p.info/now/
https://sive.rs/now
https://marcjenkins.co.uk/now/
https://www.notkindacool.com/now/
https://garrickvanburen.com/now/

---

![image](https://user-images.githubusercontent.com/17074394/130305553-b9aa24f0-db50-4b87-9a05-18563b7dff65.png)

---

There's an [aggregator website](https://nownownow.com) for now pages (showing widespread adoption).

**Comment by khusika** [comment]
if it's necessary, you can create a page for **_Now Page_** in `content/now/index.md`. Then add the link on the menu by using this frontmatter

```
  [[menu.main]]
    identifier = "Now"
    name = "Now"
    url = "/now/"
    weight = 3 #depends on your usages
```

**Comment by khusika** [comment]
Closed because _now-page_ only contains heading and sentences, no need to create a different style. And using the [_default/single.html](https://github.com/khusika/FeelIt/blob/main/layouts/_default/single.html) is enough to display the _now-page_.

> you can create a page for **_Now Page_** in `content/now/index.md`.
