### ISSUE TITLE
Example site not working

### ISSUE THREAD

**Issue by mufidu** [khusika/FeelIt#64]
### Describe the bug

Example site can't be served.

### Expected behavior

Example site serve is served through localhost.

### Screenshots

![image](https://user-images.githubusercontent.com/70360519/130567069-e6566200-18f1-46e6-8c13-4395778bf874.png)

### Build Environment

- OS: Ubuntu
- Theme version/commit: [163ae2c](https://github.com/khusika/FeelIt/commit/163ae2c042c6aa468c68aa895a59753dcc4420a6)
- Hugo version: 0.87.0

### Preview Environment

- OS: Ubuntu
- Browser: Chrome

### Proposed solution

Editing the `theme` in config.toml in exampleSite directory works for me.     
Changed it from `theme = "./"` to `theme = "../"`.

Or am I missing something here? Thanks.

**Comment by khusika** [comment]
If you are trying to debug the theme documentation, you need to cd directly from the main directories instead of exampleSite

**Comment by mufidu** [comment]
That was my first try. But I get this error instead

![image](https://user-images.githubusercontent.com/70360519/130588161-419597f0-2166-4e84-82b5-f71df4f49d77.png)

Maybe because there is no config.toml in the theme's main directory?

**Comment by khusika** [comment]
> That was my first try. But I get this error instead
> 
> ![image](https://user-images.githubusercontent.com/70360519/130588161-419597f0-2166-4e84-82b5-f71df4f49d77.png)
> 
> Maybe because there is no config.toml in the theme's main directory?

### If you have npm installed in your system, do this:
- Without production environment
  `npm run start`
- With production environment
  `npm run start-production`

### Or directly from hugo command, do this:
- Without production environment
  `hugo server --source=exampleSite --themesDir ../ -D --disableFastRender`
- With production environment
  `hugo server --source=exampleSite --themesDir ../ -D --disableFastRender -e production`

**Comment by mufidu** [comment]
Thanks! Sorry I didn't notice that.
