### ISSUE TITLE
[FEATURE] PWA Install button

### ISSUE THREAD

**Issue by horusra** [khusika/FeelIt#70]
In many instances, browsers do not even give any prompt to the user that the current site is PWA and they have the option to install it.
I suggest adding an install button to the menu (visible at all different screen sizes) that allows the users to install PWA and when it's installed to confirm that. 
For example, click "Install App", after installation has been confirmed, the button resizes to a check mark with tooltip "App is successfully installed".
![image](https://user-images.githubusercontent.com/17074394/133491403-81990b50-0bb5-4778-af43-8640d5ac5bc2.png)
![image](https://user-images.githubusercontent.com/17074394/133491519-d8589491-3c1f-4149-97d1-834b3b2f03dd.png)

Method:
https://javascript.plainenglish.io/creating-a-browser-agnostic-pwa-install-button-41039f312fbe

It could be cool if the button's text (and appearance) can then be customized in config file.
Depending on the site's use case and audience, the install button's text might need to say something other than install.

**Comment by khusika** [comment]
Creating a standalone pwa-install-button looks redundant to me. As far as I know current browsers (Chrome, Firefox, Edge) have the ability to install and detect which web has PWA support
![Screenshot from 2021-09-19 18-42-11](https://user-images.githubusercontent.com/5193379/133926332-b85cf758-eb12-4984-bb53-6442a93f6776.png)
.

**Comment by horusra** [comment]
> 
> 
> Creating a standalone pwa-install-button looks redundant to me. As far as I know current browsers (Chrome, Firefox, Edge) have the ability to install and detect which web has PWA support
> ![Screenshot from 2021-09-19 18-42-11](https://user-images.githubusercontent.com/5193379/133926332-b85cf758-eb12-4984-bb53-6442a93f6776.png)
> .

In my testing, certain configurations of browsers do not actually prompt the user, or have the install button tucked away behind menus. Most people don't even know what PWA is or that websites can be installed, so I figure having PWA functionality is wasted without making sure the user is aware of the functionality. Even on my own Firefox v93 configured for privacy, I get no download prompt whatsoever, and on Chromium Edge there's no popup, but there is an install button in the address bar if you're looking for it and know about it.
I don't think casual users will know to look for those things unless their browsers are setup in such a way that they do happen to get a popup (but even then, if they dismiss it, I don't know if they know how to get it back).

**Comment by khusika** [comment]
> Creating a standalone pwa-install-button looks redundant to me. As far as I know current browsers (Chrome, Firefox, Edge) have the ability to install and detect which web has PWA support.

Closed as of the first statement
