### ISSUE TITLE
[BUG] style customization not working

### ISSUE THREAD

**Issue by Gun9niR** [khusika/FeelIt#77]
I'm pretty new to git hub issues, and English is not my native language so please excuse me if the wording is not that proper.

## Problem

I'm trying to override the global font family of the theme using `_override.scss` described in the documentation. The file content is as follows.

```scss
@import url('https://fonts.googleapis.com/css2?family=Montserrat&display=swap');
$global-font-family: Montserrat, sans-serif;
```

But when I relaunch the site, I can see that the font `Montserrat` is requested (by looking at chrome developer tools), but the font is not set.

I also tried directly modifying the `$global_font_family` in `_variables.scss` in `/themes/FeelIt/assets/css`, but it seems only the title in the navbar header is changed. Looking at the generated scss files in `/resources/_gen/assets`, the font is still unchanged.

## Environment

I'm working on macOS M1, Hugo is installed with homebrew, command `hugo version` gives the following result

```
hugo v0.88.1+extended darwin/arm64 BuildDate=unknown
```

I'm not sure which file I should modify. Any help would be appreciated.

**Comment by mtrocadomoreira** [comment]
Hello! 

I was having the same issue, and I solved this by adding 
```
@import "_override";
@import "_custom";
```
to "assets/css/home.scss" ([see the change in my fork](https://github.com/khusika/FeelIt/compare/main...mtrocadomoreira:FeelIt:main#diff-62ddb268eb933c458786afb2994f375629eccc0e583c698eab45c31124927202)). Hope this helps!
