### ISSUE TITLE
[BUG] Zooming out (or using bigger windows) bugs out the page margins

### ISSUE THREAD

**Issue by ivangjxyz** [khusika/FeelIt#84]
### Describe the bug

Simply zoom out or use a highly horizontal screen (I know, I know...) and the wonderful margins that keep text organized and the side-ToC disappear.

### Expected behavior

There should be a maximum horizontal size of the text body, so everything is kept sanely readable while keeping the theme's background color, and the table of contents by the body. 

### Screenshots

![Screenshot_20220113_232224](https://user-images.githubusercontent.com/73471569/149418491-c56bd630-5609-4503-99c0-3018741c1262.png)

### Preview Environment

- OS: Arch Linux
- Browser: Firefox

### Additional Information

Happens with the demo website.

**Comment by khusika** [comment]
> ### Describe the bug
> Simply zoom out or use a highly horizontal screen (I know, I know...) and the wonderful margins that keep text organized and the side-ToC disappear.

Hi! thanks for your report.
I'm sure that this happens on <50% zoom-out which is not supported by our media-screen (current setting is for 4k display).
