### ISSUE TITLE
[BUG] Error on building process

### ISSUE THREAD

**Issue by loadcorp** [khusika/FeelIt#96]
### Describe the bug

Error on building process after I write the command: hugo server

> 
>[user@hugo white]$ hugo server
>Start building sites … 
>hugo v0.101.0-466fa43c16709b4483689930a4f9ac8add5c9f66+extended linux/amd64 BuildDate=2022-06-16T07:09:16Z VendorInfo=gohugoio
>ERROR 2022/06/30 22:22:47 Failed to read Git log: fatal: your current branch 'master' does not have any commits yet
>Error: Error building site: "/home/user/white/content/about/index.en.md:12:1": failed to extract shortcode: template for shortcode "style" not found
>Built in 19 ms
> 

### Screenshots

https://i.ibb.co/tQ3hqTN/2022-06-30-233449.png

### Build Environment

- OS: Fedora 34
- Theme version/commit: 1.0.1
- Hugo version: hugo_extended_0.101.0_Linux-64bit

### Preview Environment

- OS: Fedora 34

**Comment by khusika** [comment]
> ERROR 2022/06/30 22:22:47 Failed to read Git log: fatal: your current branch 'master' does not have any commits yet
 > Error: Error building site: "/home/user/white/content/about/index.en.md:12:1": failed to extract shortcode: template for shortcode "style" not found
 > Built in 19 ms

there are 2 error mentioned on your error messages:
1. Enabling gitinfo in a directory without git in it
2. Seems like you are using false statement of style shortcode
